import { useEffect } from "react";
import type { AppProps } from "next/app";
import Navbar from "../components/Layout/Navbar/Navbar";
import StyledThemeProvider from "../components/Theme/StyledThemeProvider";
import GlobalStyle from "../styles/globalStyle";
import Head from "next/head";
import Footer from "../components/Layout/Footer/Footer";
import { Provider } from "react-redux";
import NextNProgress from "nextjs-progressbar";
import { theme } from "../styles/theme";
import { store } from "../features/context/store";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Bracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <StyledThemeProvider>
          <GlobalStyle />
          <NextNProgress
            color={theme.colors.primary}
            startPosition={0.3}
            stopDelayMs={200}
            height={4}
            showOnShallow={true}
            options={{ showSpinner: false, easing: "ease", speed: 500 }}
          />
          <Navbar />
          <Component {...pageProps} />
          <Footer />
        </StyledThemeProvider>
      </Provider>
    </>
  );
}

export default MyApp;
