import type { AppProps } from "next/app";
import Navbar from "../components/Layout/Navbar";
import StyledThemeProvider from "../components/Theme/StyledThemeProvider";
import GlobalStyle from "../styles/globalStyle";
import Head from "next/head";
import Container from "../components/Common/Container";
import Footer from "../components/Layout/Footer";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>SS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledThemeProvider>
        <GlobalStyle />
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </StyledThemeProvider>
    </>
  );
}
export default MyApp;
